networks:
  backend:
    external: false

services:
  postgres:
    image: postgres
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    networks:
      - backend
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: fahrtenbuch
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - backend
